-- Schema for the over-indexing benchmark.
--
-- Creates an empty schema (sequences, tables, primary/unique keys, check constraints,
-- foreign keys) but no data. After running this, populate the schema with
-- pgbench_schema_initial_data_load.sql.
--
-- Usage:
--   createdb pgbench           -- (if it does not exist yet)
--   psql -d pgbench -f pgbench_custom_schema.sql
--
-- Notes:
--   * The seven implicit indexes that back the PRIMARY KEY / UNIQUE constraints
--     created here are the "seven initial indexes" referenced in the README:
--       1. products_pkey                           (PK on products.id)
--       2. products_sku_key                        (UNIQUE on products.sku)
--       3. products_sku_number_key                 (UNIQUE on products.sku_number)
--       4. warehouses_pkey                         (PK on warehouses.id)
--       5. stock_pkey                              (PK on stock.id)
--       6. stock_product_id_warehouse_id_key       (UNIQUE on stock(product_id, warehouse_id))
--       7. stock_movements_pkey                    (PK on stock_movements.id)
--   * pg_stat_statements is loaded via shared_preload_libraries (see postgresql.auto.conf)
--     and registered as an extension here so its views are available in this database.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

-- Sequence shared between products.sku (textual) and products.sku_number (numeric).
-- Each INSERT into products consumes two values from this sequence (one per column),
-- so sku and sku_number are not numerically aligned by design.
CREATE SEQUENCE IF NOT EXISTS global_sku_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- ---------------------------------------------------------------------------
-- products
-- ---------------------------------------------------------------------------
CREATE TABLE products (
    id          integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255)  NOT NULL,
    description text,
    sku         varchar(50)   NOT NULL UNIQUE
                  DEFAULT ('SKU-' || nextval('global_sku_seq')),
    sku_number  bigint        UNIQUE
                  DEFAULT nextval('global_sku_seq'),
    price       numeric(10,2) NOT NULL,
    created_at  timestamp without time zone DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- warehouses
-- ---------------------------------------------------------------------------
CREATE TABLE warehouses (
    id           integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(255) NOT NULL,
    location     text,
    max_capacity integer      CHECK (max_capacity > 0),
    created_at   timestamp without time zone DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- stock
--   FK to products / warehouses with ON DELETE CASCADE.
--   Quantity is constrained to be non-negative.
--   (product_id, warehouse_id) is unique to ensure one stock row per pair.
-- ---------------------------------------------------------------------------
CREATE TABLE stock (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        integer REFERENCES products(id)   ON DELETE CASCADE,
    warehouse_id      integer REFERENCES warehouses(id) ON DELETE CASCADE,
    quantity          integer NOT NULL DEFAULT 0,
    min_quantity      integer,
    max_quantity      integer,
    reorder_point     integer,
    last_restock_date timestamp without time zone,
    is_active         boolean DEFAULT true,
    location_code     varchar(20),
    batch_number      varchar(50),
    expiration_date   date,
    last_updated      timestamp without time zone DEFAULT now(),
    CONSTRAINT stock_quantity_check        CHECK (quantity >= 0),
    CONSTRAINT stock_product_warehouse_key UNIQUE (product_id, warehouse_id)
);

-- ---------------------------------------------------------------------------
-- stock_movements
--   movement_type is constrained to inbound / outbound / adjustment.
--   movement_status is constrained to completed / pending.
-- ---------------------------------------------------------------------------
CREATE TABLE stock_movements (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id         integer REFERENCES products(id)   ON DELETE CASCADE,
    warehouse_id       integer REFERENCES warehouses(id) ON DELETE CASCADE,
    quantity           integer NOT NULL,
    movement_type      varchar(50),
    movement_date      timestamp without time zone NOT NULL,
    reason_code        varchar(50),
    reference_document varchar(100),
    operator_name      varchar(100),
    approved_by        varchar(100),
    movement_status    varchar(50),
    created_at         timestamp without time zone DEFAULT now(),
    updated_at         timestamp without time zone DEFAULT now(),
    CONSTRAINT stock_movements_movement_type_check
        CHECK (movement_type IN ('inbound', 'outbound', 'adjustment')),
    CONSTRAINT stock_movements_movement_status_check
        CHECK (movement_status IN ('completed', 'pending'))
);

COMMIT;
